pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: CI
  displayName: CI Stage
  jobs:
  - job: build
    displayName: Build and Test
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'Run tests'
    - task: DotNetCoreCLI@2
      displayName: Bundle as .zip
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: '$(ArtifactName)'
        publishLocation: 'pipeline'
- stage: CD
  displayName: CD Stage
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'),
      # NOTE(jorgen.fogh): Deployment has been switched off until I get a new Azure subscription:
      False)
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: jrgfogh
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure App Service'
            inputs:
              azureSubscription: 'jrgfogh-whist - Azure'
              appType: webAppLinux
              appName: 'jrgfogh-whist'
              package: '$(Pipeline.Workspace)/$(ArtifactName)/*.zip'
